#!/bin/sh

#version="--release 0.6.6";
version="";

case `hostname` in
  (lastid) env=dev;;
  (---)    env=prod;;
  (*)      echo "Hostname unrecognized"
           exit 1
           ;;
esac

echo "---- Running on $env ----";

meteor ${version} --settings config/${env}.json
